# Generated by Django 2.2.7 on 2019-11-26 01:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_auto_20191125_1246'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(related_name='followings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='seen_movies',
            field=models.ManyToManyField(related_name='movie_seen_users', to='movies.Movie'),
        ),
    ]
