# Generated by Django 2.2.7 on 2019-11-23 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-rating',)},
        ),
    ]
