# Generated by Django 2.2.7 on 2019-11-25 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_genre_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_genres',
            field=models.ManyToManyField(related_name='genre_movies', to='movies.Genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='movie_keywords',
            field=models.ManyToManyField(related_name='keyword_movies', to='movies.Keyword'),
        ),
    ]
